python main_spectral.py \
-b 4 \
-j 4 \
-lr 1e-2 \
--steps 50 \
--epochs 60 \
--mode l1_tv_cnn \
--layer_num 50 \
--model_file save_model/spectral_fc_01.pth \
--sp_file data/SpectralResponse_9_3380.npy \
--peak_num 1 \
--sig_min 5 \
--sig_max 20 \
--gpu 1 \
--log_file "save_model/spectral_admm.log" \
--filter_num 32 \
--kernel_size 3
